### ISSUE TITLE
0.2.0 or 0.2.5 ? sketch can't update to 0.2.5

### ISSUE THREAD

**Issue by barmallion** [sigtm/sketch-style-libraries#1]

**Comment by sigtm** [comment]
Hmm yeah I just noticed the same, not sure what's going on there. I'll look into it asap

**Comment by sigtm** [comment]
@barmallion Oops, the version numbers in manifest.json and package.json didn't match, that may have caused it. It works on my end now, would you be able to try again and let me know if it works or not?

**Comment by barmallion** [comment]
))) Perfect! Thank you for plugin!

**Comment by sigtm** [comment]
Great! Please let me know if you come across any other issues :)
