### ISSUE TITLE
Sketch 50 Incompatible

### ISSUE THREAD

**Issue by llewellynathan** [sigtm/sketch-style-libraries#14]
The plugin runs an error in Sketch 50.
![bitmap](https://user-images.githubusercontent.com/10006403/39825146-591d8346-536e-11e8-9678-5c9e768d4295.png)

**Comment by sigtm** [comment]
@llewellynathan I think I managed to get the new release published now. Can you confirm if the update showed up in your plugin list, and that it works now?

**Comment by llewellynathan** [comment]
@sigtm It works! Thanks for the fix!

**Comment by sigtm** [comment]
@llewellynathan Awesome! Sorry about the delay :)
