### ISSUE TITLE
Sketch 50 error

### ISSUE THREAD

**Issue by LtBlak** [sigtm/sketch-style-libraries#15]
When Fetch from is run on a new document it gives an error
<img width="1920" alt="screen shot 2018-05-09 at 10 15 20 pm" src="https://user-images.githubusercontent.com/39133503/39829713-ee5ede64-53dc-11e8-86ec-0020d3c856ae.png">

**Comment by sigtm** [comment]
@LtBlak I think I managed to get the new release published now. Can you confirm if the update showed up in your plugin list, and that it works now?

**Comment by sigtm** [comment]
Confirmed to work in the duplicate issue so I'll close this. If the problem persists, please add a new issue :)

**Comment by LtBlak** [comment]
WOW works like a charm. Thanks a lot!
<img width="1920" alt="screen shot 2018-05-10 at 2 38 59 am" src="https://user-images.githubusercontent.com/39133503/39839926-596831ce-53fb-11e8-8927-fdb146d3a78e.png">
