### ISSUE TITLE
Delete Non-Library Styles

### ISSUE THREAD

**Issue by pietrogregorini** [sigtm/sketch-style-libraries#2]
Hey there!
First, thank you so much for the plugin, which is really useful! :)

I was wondering: is there any possibility to match the exact styles from the library, so if I delete one style in library, this will be deleted in the child Sketch document as well?

I will be more precise: I made a style in the library for testing, synced through your plugin in the child document and everything worked as a charm. Then I deleted that style in the library and I expected to be deleted in the child document as well, but this didn't happen – guess to maintain document-related styles, but sometimes would be useful to have everything synced.

This may be an enhancement, by the way, it's not a bug since I guess the plugin is expected to work like you did. Maybe this feature could be introduced as a checkbox flag while choosing the library? Just saying...

**Comment by sigtm** [comment]
Yeah that's a good idea, I've thought about it but wanted to wait and see if there was an actual demand for it. Like you mention, there is also some value in allowing document specific styles so I didn't want to make it the default behaviour :)

I will add it as soon as I have time! In the meantime, don't know if the Unused Style Remover could be of any help?

https://github.com/sonburn/unused-style-remover

**Comment by pietrogregorini** [comment]
Well, that plugin actually remove all the unused styles in the document, but would be useful in this case to not remove the ones available in the library, so that everyone who have to make a change will find the global styles all the time.

Thanks for the quick reply and consideration, btw! :)

**Comment by sigtm** [comment]
Yeah definitely, I'll see if I can add this when I have a moment!

**Comment by RaphyRaph** [comment]
+1 for that feature.

**Comment by sigtm** [comment]
Sorry for the delay on this one guys, been a hectic couple of weeks – the feature's ready now, just gotta do some testing tomorrow to make sure I haven't broken anything. The next version will have an option to delete styles that don't exist in your library (and vice versa), and it'll save your preference for each document 👍

**Comment by sigtm** [comment]
Done! @pietrogregorini & @RaphyRaph I just published version 1.0.0, where "Strict mode" lets you delete styles that don't exist in the source file (whether you're syncing to or from a library, works both ways). Let me know if you come across any problems, or think of any other feature suggestions!

**Comment by pietrogregorini** [comment]
Great! Thank you so much @sigtm
You rock! <3

**Comment by RaphyRaph** [comment]
I have found strict mode to not work properly... I have to run it multiple times because only some the style get deleted.
