### ISSUE TITLE
Replace styles to styles from library

### ISSUE THREAD

**Issue by mikeozornin** [sigtm/sketch-style-libraries#22]
Sketch 51 announced Styles Library. Now we can use styles from a library as we use symbols from the symbol library.

Previously I used Style Libraries plugin to import styles from lib to a file.

Now I want to replace imported local styles with the same styles from style library. Match by name if enough for me. There are several plugins making replace local symbols with library symbols. It will be great to have the same for styles.

**Comment by frlefebvre** [comment]
I second that. Although I would make it like the symbol swapper that already exists in that you can choose to re-map links to library A to similar styles in library B.

I have different "theme" libraries with the same style names and currently use this plugin the theme my master library of components on the fly. Relying on this new built-in feature would greatly help.

**Comment by sigtm** [comment]
Agreed! If I find time, I'll consider making a new plugin for that. Although I'm hoping someone beats me to it cause I'm gonna be pretty swamped at work the next couple months so may be hard to find time :)

In any case it's probably best to make it a separate plugin, so it doesn't imply that I'm still maintaining the actual style library functionality. That would also allow it to have a more intuitive name, so people who need to swap their styles can find it more easily.

**Comment by sigtm** [comment]
@mikeozornin & @frlefebvre: Maybe I was a bit quick to close this – I'll reopen it if it turns out that there is still some use for this plugin in parallell with the native library styles.

**Comment by frlefebvre** [comment]
@sigtm I've been working on a new plugin (based on Jason Burns' Symbol Swapper). I can't promise I will make it public as it's tied to a project I'm working on for work but I will if I can.

**Comment by sigtm** [comment]
@frlefebvre Awesome, I hope you're able to share it! I will definitely have a need for it sooner or later – let me know if you do end up making it public, I'd be happy to contribute any way I can.
