### ISSUE TITLE
Choosing "sync styles from library..." does nothing

### ISSUE THREAD

**Issue by janasoroczak** [sigtm/sketch-style-libraries#3]

**Comment by sigtm** [comment]
@janasoroczak Oops, that's not good. Would you mind checking the log output for me and see if it's giving any errors? You can find it here:

~/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log

If you run the plugin and check that immediately afterwards, there might be some clues in there, if you don't mind sharing it?

**Comment by sigtm** [comment]
@janasoroczak I pushed an update earlier today, which displays a message if it can't find any user defined libraries to sync from. If you update the plugin, is that message being displayed?

I should note that it doesn't pick up styles from the iOS library included in Sketch, only user defined libraries. I had some issues with syncing styles from non-user libraries so I didn't include them at the moment – I can look into it again if that would be a popular feature though.

**Comment by janasoroczak** [comment]
I updated the plugin and now it works perfectly. I don't use the iOS library, just custom ones so that would not be of interest, but being able to remove unused styles as they are deleted from the library would. Thanks!

**Comment by sigtm** [comment]
Awesome! Yeah that's next on the roadmap :)
