### ISSUE TITLE
Fetch document colors

### ISSUE THREAD

**Issue by marjorg** [sigtm/sketch-style-libraries#9]
Love your plugin but I think this feature could make it just a little better.

Currently I use a separate plugin to export the document colors in my Sketch Library to a JSON file and then load that into each new document I make. Would be great if that was included in your plugin to make things even easier.

The plugin I currently use is: https://github.com/andrewfiorillo/sketch-palettes

**Comment by sigtm** [comment]
Interesting idea, I don't use document colors that often so just hadn't occurred to me. I'll look into it, thanks!

**Comment by hemdrup** [comment]
Agree on this. It's would be great!

Currently keep exporting and importing the color pallet, Gradients etc. with:
https://github.com/andrewfiorillo/sketch-palettes

Not, practical for my team.

**Comment by sigtm** [comment]
@marjorg & @hemdrup: I feel bad I haven't added this yet – life has been a bit hectic both in and out of the office recently. It also looks like Sketch 51 will add library style sync natively, so I'm going to await that release before I decide if I'm going to keep maintaining this. 

My hope was always that the Sketch team would get to this eventually – looks like I got my wish sooner than expected :)

**Comment by marjorg** [comment]
@sigtm Was about to comment about Sketch 51 yesterday. I agree, probably best to wait and see how their implementation works.
